### ISSUE TITLE
Får ikke kjørt fetch data pga asyncio?

### ISSUE THREAD

**Issue by vongohren** [oyshan/fplstats#2]
![image](https://user-images.githubusercontent.com/1012055/120922103-907f8580-c6c7-11eb-9635-300a54a2d5fa.png)

Vet ikke hva jeg gjør feil her? Er ikke super python koder, så kan være jeg gjør noe gærent.
* Python 3.6.7
* Kjørte pip install med requirements in et env

**Comment by oyshan** [comment]
Ser ut til at du må bruke python 3.7+
https://stackoverflow.com/questions/52796630/python3-6-attributeerror-module-asyncio-has-no-attribute-run

**Comment by oyshan** [comment]
pyenv er ganske smud: https://github.com/pyenv/pyenv#choosing-the-python-version

**Comment by vongohren** [comment]
Ja har det, men den er litt funky for tiden :P Er ikke så mye i python så ikke altid oppsettet mitt henger med 
Sett dette før?
![image](https://user-images.githubusercontent.com/1012055/121426237-a3b67d80-c973-11eb-8f7b-8bfb14b2f8d5.png)

@oyshan

**Comment by oystein-beaufort** [comment]
Nei, det har jeg ikke sett. Man setter sånne ting opp en gang og så glemmer man hvordan man gjorde det til neste gang 🙈

**Comment by vongohren** [comment]
@oystein-beaufort i tillfelle du skulle ha mac og oppleve problemer så er dette issuene som forklarer problemet
https://github.com/pyenv/pyenv/issues/1737
https://github.com/pyenv/pyenv/issues/1740

Python og mac hadde et kollisjons problem. Fra 3.8.0 og oppver ser det ut til å være patchet.

Men jeg støttet på et nytt problem, prøvde på en annen liga og får dette issuet

<img width="1079" alt="Screen Shot 2021-06-12 at 00 34 35" src="https://user-images.githubusercontent.com/1012055/121754880-0b0c3300-cb16-11eb-867d-ade4baa6ecb9.png">

Det var ikke relatert til en hardcodet liga: https://github.com/oyshan/fplstats/pull/3 men er noe annet jeg ikke har fått sett nærmere på

**Comment by oyshan** [comment]
Ah, det ser ut som en bug i `write_file`. Mulig det kan fikses med "w+" mode i `open`?: https://stackoverflow.com/questions/2967194/open-in-python-does-not-create-a-file-if-it-doesnt-exist

Jeg har sikkert bare testa når mappene/filene allerede er der :p
