### ISSUE TITLE
Analyze crasher på noe jeg ikke helt vet hva jeg skal lete etter

### ISSUE THREAD

**Issue by vongohren** [oyshan/fplstats#5]
Har du forslag på hvordan jeg skal debugge dette?
Kan jo seff se på linjene, men om ditt python øye ser noe jeg ikke ser?
StopIteration?

<img width="1088" alt="Screen Shot 2021-06-12 at 16 17 26" src="https://user-images.githubusercontent.com/1012055/121778985-ca55fd80-cb99-11eb-968b-c7fee7121cd2.png"> 

<img width="1088" alt="Screen Shot 2021-06-12 at 16 17 09" src="https://user-images.githubusercontent.com/1012055/121778983-c924d080-cb99-11eb-92f2-386babd7259d.png">

**Comment by oystein-beaufort** [comment]
`StopIteration` betyr at man ikke fant noe som passet filteret (i dette tilfellet ingen VC, som er litt rart?). Man kan fikse det ved å f.eks. legge til en default i `next`, e.g. `next((iterable), None)`. Da raises ikke `StopIteration`

**Comment by oystein-beaufort** [comment]
Ser nå at dette kanskje skjer fordi et lag _ikke_ startet å spille / ble med i ligaen før i gw2?

**Comment by vongohren** [comment]
@oystein-beaufort nei tror jeg fant ut av hva som skjer. Den analyzeren sjekker gw1_starting_picks, finner ingen VC.
Men denne personen: https://fantasy.premierleague.com/entry/5174885/event/1 har VCen på benken så da finner den ingen ting. Fordi man valgte en VC som ble subba ut.

Skal se hva forslaget ditt kan gjøre

**Comment by oyshan** [comment]
Ah ok, da bør den lete fra alle picks da, ikke bare starting picks
